#!/usr/bin/env python3
"""
Direct SMTP Email Sender - No MCP Required
Simple and reliable email sending using Python's built-in SMTP
"""

import json
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pathlib import Path
from typing import Dict, Any, List
from dotenv import load_dotenv

# Load environment variables
load_dotenv()


def load_matched_jobs(matched_jobs_file: str) -> List[Dict[str, Any]]:
    """Load matched jobs from JSON file"""
    try:
        with open(matched_jobs_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
            return data.get('matched_jobs', [])
    except Exception as e:
        print(f"❌ Error loading matched jobs: {e}")
        return []


def format_email_body(matched_jobs: List[Dict[str, Any]]) -> str:
    """Format email body with top matched jobs"""
    email_body = "🎯 Top Job Matches Based on Your Resume\n"
    email_body += "=" * 70 + "\n\n"
    email_body += "Here are your top 50 job matches ranked by AI:\n\n"

    for i, job in enumerate(matched_jobs, 1):
        company = job.get('company', 'Unknown Company')
        position = job.get('position', 'Unknown Position')
        location = job.get('location', 'Unknown Location')
        match_score = job.get('match_score', 0)
        match_reason = job.get('match_reason', 'N/A')
        apply_link = job.get('apply_link', 'No link')

        email_body += f"{i}. {position}\n"
        email_body += f"   Company: {company}\n"
        email_body += f"   Location: {location}\n"
        email_body += f"   Match Score: {match_score}/100\n"
        email_body += f"   Why: {match_reason}\n"
        email_body += f"   Apply: {apply_link}\n"
        email_body += "\n"

    email_body += "=" * 70 + "\n"
    email_body += "🤖 Generated by AI Job Matcher\n"
    email_body += "💡 Click the apply links to view full job details.\n"

    return email_body


def send_email_smtp(recipient_email: str, subject: str, body: str) -> bool:
    """Send email using Gmail SMTP directly"""
    try:
        print("\n📧 Setting up Gmail SMTP connection...")

        # Get Gmail credentials from environment
        sender_email = os.getenv('GMAIL_USER')
        sender_password = os.getenv('GMAIL_APP_PASSWORD')

        if not sender_email or not sender_password:
            print("\n❌ Gmail credentials not found in .env file")
            print("\nPlease add to your .env file:")
            print("  GMAIL_USER=pranavipathakota@gmail.com")
            print("  GMAIL_APP_PASSWORD=your-16-char-app-password")
            print("\n📖 To get App Password:")
            print("  1. Go to https://myaccount.google.com/security")
            print("  2. Enable 2-Factor Authentication")
            print("  3. Go to 'App passwords'")
            print("  4. Create password for 'Mail'")
            print("  5. Copy 16-character password")
            print("  6. Add to .env file")
            return False

        # Create message
        print("📝 Creating email message...")
        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = recipient_email
        msg['Subject'] = subject

        # Attach body
        msg.attach(MIMEText(body, 'plain'))

        # Connect to Gmail SMTP
        print("🔌 Connecting to Gmail SMTP server...")
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()

        print("🔐 Authenticating...")
        server.login(sender_email, sender_password)

        print("📤 Sending email...")
        server.send_message(msg)
        server.quit()

        print(f"\n✅ Email sent successfully to {recipient_email}!")
        print(f"📧 From: {sender_email}")
        print(f"📋 Subject: {subject}")
        return True

    except smtplib.SMTPAuthenticationError:
        print("\n❌ Authentication failed!")
        print("\nPlease check:")
        print("  1. GMAIL_USER is correct in .env")
        print("  2. GMAIL_APP_PASSWORD is a valid 16-character app password")
        print("  3. 2-Factor Authentication is enabled on your Google account")
        print("\n💡 Generate app password at: https://myaccount.google.com/apppasswords")
        return False
    except Exception as e:
        print(f"\n❌ Error sending email: {e}")
        import traceback
        traceback.print_exc()
        return False


def main():
    """Main function"""
    print("🎯 Direct SMTP Job Email Sender")
    print("=" * 60)
    print("✅ No MCP required - uses Python SMTP directly\n")

    # Configuration
    recipient_email = os.getenv('RECIPIENT_EMAIL', 'pranavipathakota@gmail.com')

    # Get paths
    project_dir = Path(__file__).parent
    matched_jobs_file = str(project_dir / "matched_jobs" / "top_50_matches.json")

    # Check if matched jobs file exists
    if not os.path.exists(matched_jobs_file):
        print(f"❌ Matched jobs file not found: {matched_jobs_file}")
        print("💡 Please run job_matcher.py first")
        return False

    # Load matched jobs
    print("📊 Loading matched jobs...")
    matched_jobs = load_matched_jobs(matched_jobs_file)
    if not matched_jobs:
        print("❌ No matched jobs found")
        return False
    print(f"✅ Loaded {len(matched_jobs)} matched jobs")

    # Format email
    print("\n✍️  Formatting email...")
    email_body = format_email_body(matched_jobs)
    subject = f"🎯 Your Top {len(matched_jobs)} Job Matches - AI Powered"
    print(f"✅ Email formatted ({len(email_body)} characters)")

    # Send email
    success = send_email_smtp(recipient_email, subject, email_body)

    if success:
        print("\n" + "=" * 60)
        print("✅ JOB EMAIL SENT SUCCESSFULLY!")
        print("=" * 60)
        print(f"\n📬 Check your inbox: {recipient_email}")
        print("📧 Check spam folder if not in inbox")
        return True
    else:
        print("\n" + "=" * 60)
        print("❌ FAILED TO SEND EMAIL")
        print("=" * 60)
        print("\n💡 See error message above for details")
        return False


if __name__ == "__main__":
    import sys
    success = main()
    sys.exit(0 if success else 1)
