#!/usr/bin/env python3
"""
Gmail Sender for Job Matches
Sends top 50 matched jobs via Gmail using MCP server
"""

import json
import sys
import asyncio
from pathlib import Path
from typing import Dict, Any, List

# Add MCP_Servers to path to import main_app
sys.path.insert(0, str(Path(__file__).parent.parent / "MCP_Servers"))

from main_app import AIAssistant


def load_matched_jobs(matched_jobs_file: str) -> List[Dict[str, Any]]:
    """Load matched jobs from JSON file"""
    try:
        with open(matched_jobs_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
            return data.get('matched_jobs', [])
    except Exception as e:
        print(f"❌ Error loading matched jobs: {e}")
        return []


def format_email_body(matched_jobs: List[Dict[str, Any]]) -> str:
    """Format email body with top matched jobs"""
    email_body = "🎯 Top Job Matches Based on Your Resume\n"
    email_body += "=" * 70 + "\n\n"
    email_body += "Here are your top 50 job matches ranked by relevance:\n\n"

    for i, job in enumerate(matched_jobs, 1):
        company = job.get('company', 'Unknown Company')
        position = job.get('position', 'Unknown Position')
        location = job.get('location', 'Unknown Location')
        match_score = job.get('match_score', 0)
        match_reason = job.get('match_reason', 'N/A')
        apply_link = job.get('apply_link', 'No link')

        email_body += f"{i}. {position}\n"
        email_body += f"   Company: {company}\n"
        email_body += f"   Location: {location}\n"
        email_body += f"   Match Score: {match_score}/100\n"
        email_body += f"   Why: {match_reason}\n"
        email_body += f"   Apply: {apply_link}\n"
        email_body += "\n"

    email_body += "=" * 70 + "\n"
    email_body += "🤖 Generated by Job Matcher AI\n"
    email_body += "💡 Tip: Click the apply links to view full job details and submit your application.\n"

    return email_body


async def send_jobs_email(
    recipient_email: str,
    matched_jobs_file: str = "/Users/pranavi/Documents/Courses/Programming_LLMs/Project/Datathon/matched_jobs/top_50_matches.json",
    gemini_api_key: str = None
):
    """Send email with matched jobs using Gmail MCP"""
    print("📧 Job Email Sender")
    print("=" * 60)

    # Load matched jobs
    print("\n📊 Step 1: Loading matched jobs...")
    matched_jobs = load_matched_jobs(matched_jobs_file)
    if not matched_jobs:
        print("❌ No matched jobs found")
        return False
    print(f"✅ Loaded {len(matched_jobs)} matched jobs")

    # Format email
    print("\n✍️  Step 2: Formatting email...")
    email_body = format_email_body(matched_jobs)
    print(f"✅ Email formatted ({len(email_body)} characters)")

    # Initialize MCP app
    print("\n🔧 Step 3: Initializing Gmail MCP...")
    app = AIAssistant(gemini_api_key=gemini_api_key)

    try:
        # Start MCP servers
        await app.start_mcp_servers()
        print("✅ Gmail MCP server started")

        # Send email
        print("\n📤 Step 4: Sending email...")
        email_params = {
            'to': recipient_email,
            'subject': f'🎯 Your Top {len(matched_jobs)} Job Matches - AI Powered',
            'body': email_body
        }

        result = await app.send_email(email_params)
        print(f"✅ Email sent successfully!")
        print(f"   Recipient: {recipient_email}")
        print(f"   Jobs included: {len(matched_jobs)}")
        print(f"\n📋 Result: {result}")

        return True

    except Exception as e:
        print(f"❌ Error sending email: {e}")
        import traceback
        traceback.print_exc()
        return False


async def main():
    """Main function"""
    print("🎯 Job Matcher - Email Sender")
    print("=" * 60)

    # Configuration
    recipient_email = "pranavipathakota@gmail.com"  # Change this to your email
    matched_jobs_file = "/Users/pranavi/Documents/Courses/Programming_LLMs/Project/Datathon/matched_jobs/top_50_matches.json"

    # Get Gemini API key from environment
    import os
    from dotenv import load_dotenv
    load_dotenv()
    gemini_api_key = os.getenv('GEMINI_API_KEY')

    # Send email
    success = await send_jobs_email(
        recipient_email=recipient_email,
        matched_jobs_file=matched_jobs_file,
        gemini_api_key=gemini_api_key
    )

    if success:
        print("\n" + "=" * 60)
        print("✅ JOB EMAIL SENT SUCCESSFULLY!")
        print("=" * 60)
        print(f"\n📬 Check your inbox: {recipient_email}")
    else:
        print("\n" + "=" * 60)
        print("❌ FAILED TO SEND EMAIL")
        print("=" * 60)
        sys.exit(1)


if __name__ == "__main__":
    asyncio.run(main())
